/*
add avatar 
add cimage
add token
*/
CREATE TABLE ADOPTION_AGENCY(
    AGENCY_ID NUMBER(5) PRIMARY KEY,
    ANAME VARCHAR2(50),
    USER_ID NUMBER(5),
    ADRESS VARCHAR2(50),
    EMAIL VARCHAR2(25) UNIQUE,
    PHONE_NO NUMBER(15) UNIQUE,
    WEBSITE VARCHAR2(100),
    LICSENCE_NO NUMBER(10),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
)
CREATE SEQUENCE AGENCY_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;
CREATE TABLE AGENCY_CHILD_RELATION(
    AGENCY_ID INT,
    CHILD_ID INT,
    FOREIGN KEY(AGENCY_ID) REFERENCES ADOPTION_AGENCY(AGENCY_ID),
    FOREIGN KEY(CHILD_ID) REFERENCES CHILD(CID)
)