CREATE TABLE ADOPTION_AGENCY(
    AGENCY_ID INT PRIMARY KEY,
    ANAME STRING,
    USER_ID NUMBER(5),
    ADRESS VARCHAR2(50),
    EMAIL STRING UNIQUE,
    PHONE_NO NUMBER(15) UNIQUE,
    WEBSITE STRING,
    LICSENCE_NO STRING,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)
CREATE TABLE AGENCY_CHILD_RELATION(
    AGENCY_ID INT,
    CHILD_ID INT,
    FOREIGN KEY(AGENCY_ID) REFERENCES ADOPTION_AGENCY(AGENCY_ID),
    FOREIGN KEY(CHILD_ID) REFERENCES CHILD(CID)
)