CREATE TABLE BOOKING(
    BOOKING_ID INT PRIMARY KEY,
    PARENT_ID INT,
    CHILD_ID INT,
    DOCUMENT_ID INT,
    FOREIGN KEY(PARENT_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(CHILD_ID) REFERENCES CHILD(CID),
    FOREIGN KEY(DOCUMENT_ID) REFERENCES DOCUMENT(DID)
)