CREATE TABLE CHILD(
    CID INT PRIMARY KEY,
    CNAME STRING,
    GENDER CHAR,
    CDOB DATE,
    DATE_OF_ENTRY DATE,
    DESCRIPTION VARCHAR2(100),
    PHOTO STRING,
    STATUS VARCHAR2(10) CHECK(STATUS IN ('Available', 'Adopted','Waiting')),
    MEDICAL_HISTORY_ID INT,
    HOBBY STRING,
    AGENCY_ID INT,
    FOREIGN KEY(MEDICAL_HISTORY_ID) REFERENCES MEDIACL_HISTORY(MEDICAL_HISTORY_ID),
    FOREIGN KEY (AGENCY_ID) REFERENCES ADOPTION_AGENCY(AGENCY_ID)
)