CREATE TABLE CHILD(
    CID NUMBER(5) PRIMARY KEY,
    CNAME VARCHAR2(25),
    GENDER VARCHAR2(10),
    CDOB DATE,
    DATE_OF_ENTRY DATE,
    DESCRIPTION VARCHAR2(150),
    PHOTO VARCHAR2(100),
    STATUS VARCHAR2(12) CHECK(STATUS IN ('Available', 'Adopted','Waiting')),
    HOBBY VARCHAR2(100),
    AGENCY_ID NUMBER(5),
    FOREIGN KEY (AGENCY_ID) REFERENCES ADOPTION_AGENCY(AGENCY_ID)
)
CREATE SEQUENCE CHILD_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;