    CREATE TABLE CUSTOMER(
        CUSTOMER_ID NUMBER(5) PRIMARY KEY,
        USER_ID NUMBER(5),
        FATHERS_NAME VARCHAR2(50),
        FATHERS_AGE NUMBER(3) CHECK(FATHERS_AGE>21),
        MOTHERS_NAME VARCHAR2(50),
        MOTHERS_AGE NUMBER(3) CHECK(MOTHERS_AGE>20),
        EMAIL1 VARCHAR2(50) UNIQUE,
        EMAIL2 VARCHAR2(50) UNIQUE,
        PHONE_NO1 VARCHAR2(15) UNIQUE,
        PHONE_NO2 VARCHAR2(15) UNIQUE,
        ADDRESS VARCHAR2(50),
        ADOPTION_HISTORY VARCHAR2(50),
        PROFILE_STATUS VARCHAR2(10) CHECK(PROFILE_STATUS IN ('Verified','Not Verfied')),
        BIO VARCHAR2(50),
        FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
    )