CREATE TABLE MEDICAL_HISTORY(
    MEDICAL_HISTORY_ID INT PRIMARY KEY,
    CHILD_ID INT,
    AGE INT,
    WEIGHT INT,
    HEIGHT  INT,
    IS_DISEASE VARCHAR2(3),
    DISEASE_NAME STRING,
    DISEASE_DESCRIPTION VARCHAR2(100),
    TREATEMENT_DESCRIPTION VARCHAR2(150),
    TREATEMENT_START_DATE DATE,
    TREATEMENT_END_DATE DATE,
    IS_CHRONIC VARCHAR2(3) CHECK(IS_CHRONIC IN ('Yes','No')),
    DOC_NAME STRING,
    HOSPITAL_NAME STRING,
    NOTE STRING,
    FOREIGN KEY(CHILD_ID) REFERENCES CHILD(CID)
)