CREATE TABLE ADOPTION_REQ(
    REQID INT PRIMARY KEY,
    PARENT_ID INT,
    CHILD_ID INT,
    REQUEST_DATE DATE,
    STATUS STRING CHECK(STATUS IN ('Approved','Rejected','Waiting')),
    APPROVAL_DATE DATE,
    AGENCY_ID INT,
    COMMENTS VARCHAR2(100),
    FOREIGN KEY(PARENT_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(CHILD_ID) REFERENCES CHILD(CID),
    FOREIGN KEY(AGENCY_ID) REFERENCES ADOPTION_AGENCY(AGENCY_ID)
)