CREATE TABLE SCHEDULING(
    SID INT PRIMARY KEY,
    CHILD_ID INT ,
    PARENT_ID INT,
    AGENCY_ID INT,
    SCHEDULING_DATE DATE,
    SCHEDULING_SHIFT STRING CHECK(SCHEDULING_SHIFT IN ('Day Shift','Evening Shift')),
    FOREIGN KEY(CHILD_ID) REFERENCES CHILD(ID),
    FOREIGN KEY(PARENT_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(AGENCY_ID) REFERENCES ADOPTION_AGENCY(AGENCY_ID)
)