CREATE TABLE USERS(
    USER_ID NUMBER(5),
    USERNAME VARCHAR2(20),
    EMAIL VARCHAR2(50) UNIQUE NOT NULL,
    PHNO VARCHAR2(15) UNIQUE NOT NULL,
    REFRESH_TOKEN VARCHAR2(250),
    AVATAR VARCHAR2(250),
    PASSWORD VARCHAR2(100) NOT NULL,
    PRIMARY KEY(USER_ID,USERNAME)
)
CREATE SEQUENCE USER_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;
